### ISSUE TITLE
Issue - node version v10.12.0

### ISSUE THREAD

**Issue by symis84** [MMhunter/node-sync-ipc#4]
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/trpeu72/Desktop/4Casters_Angular6_Electron/4casters-console-ng6/node_modules/node-sync-ipc/build/Release/server.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/trpeu72/Desktop/4Casters_Angular6_Electron/4casters-console-ng6/node_modules/node-sync-ipc/build/Release/server.node
  Expected in: flat namespace

**Comment by symis84** [comment]
OS: Mac OS high sierra, 10.13.6
I think the problem is related to node-gyp incorrectly setting MACOSX_DEPLOYMENT_TARGET to another osx version.

**Comment by MMhunter** [comment]
@symis84 hi, it looks like that you are trying to use this lib in Electron 3.x maybe? It need to be rebuilt by `electron-rebuild`. Or u may manually rebuilt it by going to `node-sync-ipc` 's  dir and run 

````
HOME=~/.electron-gyp node-gyp rebuild --target=3.0.5 --arch=x64 --dist-url=https://atom.io/download/atom-shell
````

The target version is the electron you are using.
