### ISSUE TITLE
Broadcast functionality ?

### ISSUE THREAD

**Issue by myfreescalewebpage** [MMhunter/node-sync-ipc#5]
Hi,
Great work here, very nice lib!
Question I have now is: any plan to have some kind of broadcast from the server to all clients ?
Thanks for your response,
Joel

**Comment by MMhunter** [comment]
Thanks.

But it seems that a broadcasting pattern is not suitable for this lib. It is an asynchronous communication and you can achieve that by using a lot of other wonderful libs like traditional node-ipc or etc.

**Comment by myfreescalewebpage** [comment]
Thanks @MMhunter for your answer, I will have a look to another solution.
Again great job here!
Closing the issue.
Joel
